// src/app/views/counter/counter.component.ts
import { Component, OnInit, HostListener } from '@angular/core';

@Component({
  selector: 'app-counter',
  templateUrl: './counter.component.html',
  styleUrls: ['./counter.component.scss']
})
export class CounterComponent implements OnInit {
  count: number = Number(localStorage.getItem("count") ?? 0);
  increment = () => this.count++;

  constructor(){}

  ngOnInit(): void {}
  
  @HostListener("window:unload")
  saveToLocalStorage(){
    localStorage.setItem("count", this.count.toString());
  }
}

<button class="counter" (click)="increment()">
	<div fontSize="1.25rem">Click Me</div>
	<div class="count">{{ count }}</div>
</button>

// src/views/counter.tsx
import * as React from 'react';
import { useState } from 'react';
import { 
	Box, 
	Button, 
	Center, 
	Flex
} from '@chakra-ui/react';
 
const Counter: React.FC = () => {

	const [count, setCount] = useState(localStorage.getItem("count") ?? 0);

	window.onunload = () => {
		localStorage.setItem("count", count.toString());
	};

	return (
		<Box mt='2rem'>
			<Center>
				<Button
					onClick={() => setCount(y => Number(y) + 1)}
					py='16rem'
					px='15rem'
					borderRadius='100%'
					boxShadow='0.65rem 0.65rem 1rem 1px rgba(0, 0, 0, 0.3)'
				>
					<Flex flexDirection='column' gap={2}>
						<Box>Click Me</Box>
						<Box fontSize={20}>{count}</Box>
					</Flex>
				</Button>
			</Center>
		</Box>
	);
};

export default Counter;
