// src/views/about.tsx
import * as React from 'react';
import { Container, Box } from '@chakra-ui/react';

/* eslint react/jsx-one-expression-per-line: 0 */
const About: React.FC = () => (
	<Container maxW='container.md'>
		<Box fontSize={48} mb={7}>
			About <span style={{ fontWeight: 'bold' }}>Clark</span>
		</Box>
		<Box>
			This GitHub page is used to store some info from my repos. <br />
		</Box>
	</Container>
);

export default About;

// src/app/views/about/about.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './about.component.html',
  styles: [`
    .c {
      display: grid;
      gap: 1rem;
    } 
  `]
})
export class AboutComponent implements OnInit {
  constructor() {}
  ngOnInit(): void {
  }
}

<div class="c">
	<div fontSize="3rem" [style]="{marginTop:'1rem'}">About <b>Clark</b></div>
	<div [style]="{margin: '1.25rem 0'}" fontSize="1rem">This GitHub page is used to store some info from my repos.</div>
</div>
